apiVersion: 1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sdc3
    labels:
      app: sdc3
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: sdc3
    template:
      metadata:
        labels:
          app: sdc3
      spec:
        containers:
        - name: sdc3
          image: streamsets/datacollector:latest
          ports:
          - containerPort: 18630
          env:
          - name: SDC_JAVA_OPTS
            value: "-Xmx4g -Xms4g"
          - name: SDC_CONF_SDC_BASE_HTTP_URL
            value: https://sdc3.onefoursix.com
          - name: SDC_CONF_HTTP_ENABLE_FORWARDED_REQUESTS
            value: true
- apiVersion: v1
  kind: Service
  metadata:
    name: sdc3
    labels:
      app: sdc3
  spec:
    type: NodePort
    ports:
    - name: http
      port: 18637
      targetPort: 18630
      protocol: TCP
    selector:
      app: sdc3
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: sdc3
    annotations:
      kubernetes.io/ingress.class: nginx
  spec:
    tls:
    - hosts:
      - sdc3.onefoursix.com
      secretName: streamsets-tls
    rules:
    - host: sdc3.onefoursix.com
      http:
        paths:
        - path: /
          backend:
            serviceName: sdc3
            servicePort: 18637