
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-sdc
  labels:
    app: auth-sdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-sdc
  template:
    metadata:
      labels:
        app: auth-sdc
    spec:
      containers:
      - name: auth-sdc
        image: streamsets/datacollector:latest
        ports:
        - containerPort: 18630
        env:
        - name: SDC_JAVA_OPTS
          value: "-Xmx4g -Xms4g"
        volumeMounts:
        - name: my-secrets
          mountPath: /etc/sdc/my-keystore.jks
          subPath: my-keystore.jks
        - name: my-secrets
          mountPath: /etc/sdc/my-truststore.jks
          subPath: my-truststore.jks
      volumes:
      - name: my-secrets
        secret:
          secretName: my-secrets
          items:
          - key: my-keystore.jks
            path: my-keystore.jks
          - key: my-truststore.jks
            path: my-truststore.jks
