apiVersion: 1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sdc-microservice
    labels:
      app : sdc-microservice
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: sdc-microservice
    template:
      metadata:
        labels:
          app: sdc-microservice
      spec:
        containers:
        - name : sdc-microservice
          image: streamsets/datacollector:latest
          ports:
          - containerPort: 18630
          env:
          - name: SDC_JAVA_OPTS
            value: "-Xmx2g -Xms2g"
- apiVersion: v1
  kind: Service
  metadata:
    name: sdc-microservice
    labels:
      app: sdc-microservice
  spec:
    type: LoadBalancer
    ports:
    - name: sdc-microservice
      port: 18800
      targetPort: 18700
      protocol: TCP
    selector:
      app: sdc-microservice
